//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Second_Try.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHIHUNG\\SQLEXPRESS01;Initial Catalog=Quan_ly-firsttry;Integrated Secu" +
            "rity=True;Encrypt=True;TrustServerCertificate=True")]
        public string Quan_ly_firsttryConnectionString {
            get {
                return ((string)(this["Quan_ly_firsttryConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHIHUNG\\SQLEXPRESS01;Initial Catalog=Quan_ly_secondtry;Integrated Sec" +
            "urity=True;TrustServerCertificate=True")]
        public string Quan_ly_secondtryConnectionString {
            get {
                return ((string)(this["Quan_ly_secondtryConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=PHIHUNG\\SQLEXPRESS01;Initial Catalog=QuanLyLichKham;Integrated Securi" +
            "ty=True;Encrypt=True;TrustServerCertificate=True")]
        public string QuanLyLichKhamConnectionString {
            get {
                return ((string)(this["QuanLyLichKhamConnectionString"]));
            }
        }
    }
}
